# Generated by Django 6.0.6 on 2026-07-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('module', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15)),
                ('skill', models.CharField(choices=[('letter_recognition', 'Letter Recognition'), ('letter_sounds', 'Letter Sounds'), ('word_recognition', 'Word Recognition'), ('reading_fluency', 'Reading Fluency'), ('writing', 'Writing'), ('vocabulary', 'Vocabulary'), ('comprehension', 'Comprehension'), ('grammar', 'Grammar'), ('sentence_formation', 'Sentence Formation')], max_length=30)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ta', 'Tamil')], max_length=2)),
                ('estimated_time', models.PositiveIntegerField(help_text='Minutes')),
                ('audio_text', models.CharField(blank=True, help_text="Text to be spoken aloud via TTS for this lesson's instruction/content", max_length=500)),
                ('image_emoji', models.CharField(blank=True, help_text='Placeholder visual (emoji) until real illustrated images are designed', max_length=10)),
                ('quiz', models.JSONField(blank=True, default=dict)),
                ('voice_activity', models.CharField(blank=True, help_text='Word/phrase the learner is prompted to say aloud (speech recognition target)', max_length=300)),
                ('order_in_level', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['difficulty', 'language', 'order_in_level'],
            },
        ),
    ]
