# Generated by Django 6.0.6 on 2026-07-18 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('users', '0003_alter_learner_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('completed', 'Completed')], default='locked', max_length=15)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path', to='users.learner')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_entries', to='lessons.lesson')),
            ],
            options={
                'ordering': ['learner', 'day_number'],
                'unique_together': {('learner', 'day_number')},
            },
        ),
    ]
