# Generated by Django 6.0.6 on 2026-07-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_learningpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='activities_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio_assets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lesson',
            name='internal_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(default='tap_letters', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='prerequisite_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lesson',
            name='rewards_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lesson',
            name='visual_assets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
