# Generated by Django 6.0.6 on 2026-07-09 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('comprehension', 'Comprehension')], max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ta', 'Tamil')], max_length=2)),
                ('group_key', models.CharField(max_length=50)),
                ('passage_text', models.TextField(blank=True, null=True)),
                ('question_text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('text_input', 'Text Input')], max_length=20)),
                ('option_a', models.CharField(blank=True, max_length=200, null=True)),
                ('option_b', models.CharField(blank=True, max_length=200, null=True)),
                ('option_c', models.CharField(blank=True, max_length=200, null=True)),
                ('option_d', models.CharField(blank=True, max_length=200, null=True)),
                ('correct_answer', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['assessment_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('comprehension', 'Comprehension')], max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ta', 'Tamil')], max_length=2)),
                ('score', models.FloatField()),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_count', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='users.learner')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_answer', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessmentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmentquestion')),
            ],
        ),
        migrations.CreateModel(
            name='LiteracyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_score', models.FloatField(default=0)),
                ('writing_score', models.FloatField(default=0)),
                ('comprehension_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='literacy_profile', to='users.learner')),
            ],
        ),
    ]
