# Generated by Django 6.0.6 on 2026-07-13 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_questions', to='users.learner')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmentquestion')),
            ],
            options={
                'unique_together': {('learner', 'question')},
            },
        ),
    ]
