# Generated by Django 6.0.6 on 2026-07-15 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_seenquestion'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='is_initial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='skill_tag',
            field=models.CharField(blank=True, choices=[('letter_recognition', 'Letter Recognition'), ('word_recognition', 'Word Recognition'), ('literal_comprehension', 'Literal Comprehension'), ('inferential_comprehension', 'Inferential Comprehension'), ('writing_fluency', 'Writing Fluency'), ('writing_vocabulary', 'Writing Vocabulary')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='SkillBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_tag', models.CharField(max_length=30)),
                ('score', models.FloatField()),
                ('band', models.CharField(choices=[('weak', 'Weak'), ('average', 'Average'), ('strong', 'Strong')], max_length=10)),
                ('attempts_counted', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_breakdowns', to='users.learner')),
            ],
            options={
                'unique_together': {('learner', 'skill_tag')},
            },
        ),
    ]
