# Generated by Django 6.0.6 on 2026-07-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessmentattempt_is_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentattempt',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ml', 'Malayalam')], max_length=2),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ml', 'Malayalam')], max_length=2),
        ),
    ]
