# Generated by Django 6.0.6 on 2026-08-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_studysession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PronunciationScore',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_id', models.CharField(default='custom_practice', max_length=100)),
                ('expected_text', models.TextField()),
                ('transcribed_text', models.TextField(blank=True, null=True)),
                ('content_score', models.FloatField(default=0.0)),
                ('pronunciation_score', models.FloatField(default=0.0)),
                ('fluency_score', models.FloatField(default=0.0)),
                ('speech_rate', models.FloatField(default=0.0)),
                ('pause_count', models.IntegerField(default=0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_scores', to='users.learner')),
            ],
        ),
        migrations.CreateModel(
            name='SpeechAttempt',
            fields=[
                ('attempt_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_id', models.CharField(default='custom_practice', max_length=100)),
                ('audio_path', models.CharField(blank=True, max_length=255, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_attempts', to='users.learner')),
            ],
        ),
    ]
