# Generated by Django 6.0.6 on 2026-07-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ar', 'Arabic')], max_length=2)),
                ('avatar', models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('grandmother', 'Grandmother'), ('grandfather', 'Grandfather'), ('teacher', 'Teacher'), ('book', 'Book'), ('lion', 'Lion'), ('tiger', 'Tiger'), ('apple', 'Apple'), ('flower', 'Flower'), ('star', 'Star'), ('migo', 'MiGo Mascot')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
