# Generated by Django 6.0.6 on 2026-07-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_learner_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ta', 'Tamil')], max_length=2),
        ),
    ]
