# Generated by Django 6.0.6 on 2026-07-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_learner_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='known_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ta', 'Tamil')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='learner',
            name='learning_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ta', 'Tamil')], default='en', max_length=2),
        ),
    ]
