# Generated by Django 6.0.6 on 2026-07-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_learner_known_language_learner_learning_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='users.learner')),
            ],
        ),
    ]
