# Generated by Django 6.0.6 on 2026-08-11 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_studysession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='learner',
            name='phone_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners', to='users.phoneaccount'),
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('phone_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='users.phoneaccount')),
            ],
            options={
                'unique_together': {('phone_account', 'device_id')},
            },
        ),
    ]
