# Generated by Django 6.0.6 on 2026-08-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_book_learner_subscription_tier_communitypost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audio_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(default='Story', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='google_play_url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.CharField(default='Free', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name='book',
            name='why_recommended',
            field=models.TextField(default=''),
        ),
    ]
