# Generated by Django 6.0.6 on 2026-08-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneaccount',
            name='phone_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
