# Generated by Django 6.0.6 on 2026-08-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_phoneaccount_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
        migrations.AddField(
            model_name='phoneaccount',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
